# Generated by Django 2.1.5 on 2019-03-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
